server:
  assets-path: /app/assets

theme:
  presets:
    cattpuccin-dark:
        light: false
        background-color: 232 23 18
        contrast-multiplier: 1.2
        primary-color: 220 83 75
        positive-color: 105 48 72
        negative-color: 351 74 73

    cattpuccin-light:
        light: true
        background-color: 220 23 95
        contrast-multiplier: 1.0
        primary-color: 220 91 54
        positive-color: 109 58 40
        negative-color: 347 87 44
  custom-css-file: /assets/user.css


pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  - $include: home.yml
